### ISSUE TITLE
using laptop as OTBR

### ISSUE THREAD

**Issue by kwangeom** [openthread/borderrouter#154]
This is question, not a bug. I am not sure where to post this.
I am trying to use my laptop, which has Ubuntu 16.04.4 LTS installed, as openthread borderrouter. But I don't see wpan0 interface after installation complete.
This is what I did.
1. git clone https://github.com/openthread/borderrouter
2. cd borderrouter
3. ./script/bootstrap && ./script/setup 
4. modify /etc/wpantund.conf to add ttyACM0.
5. attached NCP device and power cycled
6. no wpan0 interface after rebooot.
7. cd borderrouter/._build/wpantund
8. ./bootstrap.sh
9. ./configure --sysconfdir=/etc
10. make && make install
11. modify /etc/wpantund.conf to add ttyACM0 since overwritten by 8,9,10
12. kill running wpantund process
13. /usr/local/sbin/wpantund in one window
14. ifconfig in another window, but still no wpan0
15. wpanctl status, it shows
wpan0=> [
                 "NCP:State" => "offline"
                .....
    this looks good
16. open browser and enter ip address of the laptop
17. run "form network", but never successful.

I don't have any issue on OTBR with BBB and RPI3. but I want to use my laptop as OTBR too because it could be easier to debug any application running on that.
Anybody experience on laptop as OTBR?

**Comment by bukepo** [comment]
@kwangeom sorry for the late. 
I'm wondering if */dev/ttyACM0* is available when wpantund starts. Try manually restart wpantund and check the logs. If it didn't help, could you please share your logs so that we can analyze?

Besides, your manually installation may result in two *wpantund*s. If you want to manually build, it's better to configure just as the script does.

**Comment by bukepo** [comment]
@kwangeom is this still an issue for you?

**Comment by jwhui** [comment]
Closing stale issue.
